### PR TITLE
Fix the menu render issue in Big Sur 11.0.1

### PR DESCRIPTION
**Pull request by goodbest**
https://github.com/osy86/HaC-Mini/issues/316#issuecomment-731743555

The true explanation why the patch is working remains unknown yet, since  `21` is a magical value in the dyld.
The following is the logic why I try the number 0.

- The original Big Sur use an statement:
`if somevalue <21, then do sth.`
Glitches are everywhere.

- the current kext is patched to do the statement:
`if somevalue >=21, then do sth.`
The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
However it's working partially in big sur.

- So I replace the value 21 to 0:
`if somevalue >=0, then do sth.`
And it's working now, with no side effect found yet.

BTW, since I suppose a value between 0 and 21 would be better, I tried with different numbers for HVK.
The patch is working with the patch `if somevalue >=19`, but no with `somevalue >=20`.
However, I think it's still better to use `if somevalue >=0` if there's no obvious side effect.

image
image

This PR will close 
https://github.com/osy86/Polaris22Fixup/issues/10
https://github.com/osy86/HaC-Mini/issues/316

Potentially close:
https://github.com/osy86/HaC-Mini/issues/392

### CODE REVIEW

**Comment by keatliang2005** [comment]
I wonder the VRAM usage is about the same ? 
I didn't run any 3D APP, just chrome with youtube. that's it 

Screenshot 2020-11-23 at 8 15 37 PM

**Comment by goodbest** [comment]
This may be a system issue, not related to the patch.

For the record, I'm using the kext all the time.
Before 20:19, the VRAM is 99% but I did nothing other than Chrome.

After 20:19, I reboot the device, and start playing StarCraft2 (with metal engine).
The VRAM remains ~30%, but the GPU processor reaches 99%(which means the game uses a lot calculations) 

VRAM:
image

GPU Processors
image

**Comment by osy** [comment]
Cool, can you confirm that Metal isn’t disabled? By running a Geekbench Metal compute?

EDIT: ah didn’t see the comment in the other thread. Seems like you’ve already tried it.

**Comment by keatliang2005** [comment]
@osy86 , @goodbest 

I have run the Geekbench 5 test, looks good

Screenshot 2020-11-25 at 12 14 51 PM

**Comment by osy** [comment]
Thanks, I’ll include this in the next release.

**Comment by davidwuya** [comment]
My VRAM usage is also topping up when I use Chrome. Might be a bug, but haven't noticed any side effects yet.
image

**Pull request merged**
